### ISSUE TITLE
part# for CPU connector and RPi connector

### ISSUE THREAD

**Issue by alestanga** [captain-amygdala/pistorm#10]
hello,
I've just ordered the PCBs from JLCPCB and I'm about to order the components from LCSC.
since there is no CPU connector in the BOM, do you have any suggestion about which one to buy?
I've already built an Open Amiga 500 RAM Expansion but it ended up being to tall to fit in the case so, I'd like to buy one that fits inside :)
also, for the RPi, I'm buying this one from LCSC: C350274
is it too tall or could work?
I've also seen the metal screws and nuts in some pictures, are those really necessary?
In my A314 the raspberry is kept in place only by the 40 pins connector.
thanks.

**Comment by madgrizzle** [comment]
May want to post this question on the discord channel:

https://discord.gg/qnzEXnPh

There's a lot of activity there and there was a recent discussion regarding this topic.

**Comment by alestanga** [comment]
thank you, I'll join the channel.
I didn't know about there was a discord channel.
