### ISSUE TITLE
small & cheap speedup

### ISSUE THREAD

**Issue by jotd666** [captain-amygdala/pistorm#11]
in m68kcpu.c you'll see that this code

/* Record previous D/A register state (in case of bus error) */
			for (i = 15; i >= 0; i--){
				REG_DA_SAVE[i] = REG_DA[i];
			}

copies data registers at each instruction execution, but REG_DA_SAVE isn't used (except in case of bus error, but I didn't find where it was actually used)

If you remove it you probably save a few cycles :)

(note: I contributed to this latest version of musashi, specially on the 68040 fpu stuff, see "JFF" comments that were left there)

**Comment by captain-amygdala** [comment]
Thanks for the hint !  It's already integrated in our Mushasi :)
