### ISSUE TITLE
[Makefile:69: emulator] Error 1 on install

### ISSUE THREAD

**Issue by peterkomorowski** [captain-amygdala/pistorm#50]
I get the same error after attempting a "make".  Tried two different SD Cards.  Any suggestions?

**Comment by Banos1337** [comment]
> I get the same error after attempting a "make". Tried two different SD Cards. Any suggestions?

Same here. Tried the process from scratch. no luck :(

**Comment by Banos1337** [comment]
> I get the same error after attempting a "make". Tried two different SD Cards. Any suggestions?

Read section below:
Important note: If you are using Raspberry Pi OS "Bullseye", the main graphics backend for the OS has changed from dispmanx to DRM, and you need to follow these steps instead of just running make:

**Comment by captain-amygdala** [comment]
Some more details would be helpful. Which OS is used, which options on 'make' , unclear parts of the readme/howto so that we can improve it on these parts.

**Comment by captain-amygdala** [comment]
closing
