### ISSUE TITLE
SD CARD ACT LED overriden

### ISSUE THREAD

**Issue by JaneDoe649** [captain-amygdala/pistorm#56]
Thanks for this project and all the work done.

I made a little schematic in order to drive AMIGA 2000 hard drive activity LED through the PI ACT LED. It worked well during the raspian's loading. But when the emulator was running the LED stayed off.  I saw  in "ps_protocol.h" that the GPFSEL2_OUTPUT and GPFSEL2_INPUT constants forced GPIO29 as input. This GPIO drives ACT LED of PI ZERO 2W I use.

So I made this changes forcing GPIO29 as output and the AMIGA HDD LED took live :)
#define GPFSEL2_OUTPUT 0x00000249 replaced by **0x8000249**
#define GPFSEL2_INPUT    0x00000000 replaced by  **0x08000000**

I hope this issue could be usefull.
![Schematic](https://user-images.githubusercontent.com/68509630/170677291-d2b9ee67-50e2-4a0e-9966-0dc7c0f72339.png)

**Comment by captain-amygdala** [comment]
Thanks! For future updates we keep that in mind.
