### ISSUE TITLE
emulator problems

### ISSUE THREAD

**Issue by Perits36** [captain-amygdala/pistorm#75]
This what I get when invoking emulator.
I have followed your instructions to the letter, but as can be seen below to no avail.
Pls help.
/Sal
(sal(at)gribsvad(dot)com
pi@raspberrypi:~/pistorm $ sudo ./emulator --config amiga.config
Config file amiga.config does not exist, please check that you've specified the path correctly.
No config file specified. Trying to load default.cfg...
[CFG] Failed to open config file default.cfg for reading.
Couldn't load default.cfg, empty emulator config will be used.
Creating platform config for none...
No IDE drives mounted, disabling Gayle IDE component.
Setting CPU type to 1.

^CReceived sigint 2, exiting.
IRQs triggered: 0
IRQs serviced: 0
Last serviced IRQ: 8

**Comment by LemaruX** [comment]
If you follow the instructions properly,  you will see it's amiga.cfg and not amiga.config.

Specify the correct file and it will work. 

amiga.cfg is only really there to be used as a template. If you copy it to a new file called default.cfg then you don't need to specify it when running the emulator, as it will load it automatically.

**Comment by Perits36** [comment]
Thanks for your rapid reply. I realized my mistake with the config file almost as I send the mail. Having said that I unfortunately get the same result with the config corrected. IE now amiga window:( A thought, can the reason be that the A1200 has no fast mem?

/Sal

**Comment by LemaruX** [comment]
The Pi provides the fast ram via the PiStorm.

Are you sure you are using the correct branch and following the correct instructions? You need to be using the PiStorm32 branch, and following the he instructions there 

https://github.com/captain-amygdala/pistorm/tree/pistorm32-lite

Also make sure you are using the correct command to run the emulator (you need to specify the bitstream when running it)

**Comment by LemaruX** [comment]
Just to add, as this is a general support issue, and not really an issue with the PiStorm software, it would probably be easier to head over to the discord server where it'll be easier for us to help with your issue.

**Comment by Perits36** [comment]
Again, thank you for your quick response.

I didn't invoke the bitstream part before but it appears it dosn't make any difference(:

I am attaching my amiga.cfg and the result when issuing the same.

I hope for your help and at the same time hope you aren't getting tired of this.

Kind regards,

Sal

**Comment by LemaruX** [comment]
Unfortunately nothing has been attached.

Check the readme on GitHub and you will find a link to the discord server where we have dedicated support channels.

If you head there it will be much easier to provide support than it is here
